version: "3.7"

services:
  db-ride-service:
    image: postgres
    ports:
      - '5444:5432'
    environment:
      POSTGRES_PASSWORD: ${dbPassword}
      POSTGRES_USER: ${dbUsername}
      POSTGRES_DB: client-db
